export const engineeringColleges = [
  {
    id: 1,
    name: "Sri Venkateswara College of Engineering, Tirupati",
    latitude: 13.6174,
    longitude: 79.4219,
  },
  {
    id: 2,
    name: "Sree Vidyanikethan Engineering College, Tirupati",
    latitude: 13.6288,
    longitude: 79.5121,
  },
  {
    id: 3,
    name: "Chadalawada Ramanamma Engineering College, Tirupati",
    latitude: 13.6286,
    longitude: 79.4296,
  },
  {
    id: 4,
    name: "Annamacharya Institute of Technology and Sciences, Tirupati",
    latitude: 13.6731,
    longitude: 79.4336,
  },
  {
    id: 5,
    name: "SV University College of Engineering, Tirupati",
    latitude: 13.6312,
    longitude: 79.412,
  },
  {
    id: 6,
    name: "JNTU College of Engineering, Anantapur",
    latitude: 14.6812,
    longitude: 77.6005,
  },
  {
    id: 7,
    name: "RVR & JC College of Engineering, Guntur",
    latitude: 16.2626,
    longitude: 80.3587,
  },
  {
    id: 8,
    name: "Gayatri Vidya Parishad College of Engineering, Visakhapatnam",
    latitude: 17.7941,
    longitude: 83.3736,
  },
  {
    id: 9,
    name: "Vasavi College of Engineering, Hyderabad",
    latitude: 17.3936,
    longitude: 78.3923,
  },
  {
    id: 10,
    name: "Andhra University College of Engineering, Visakhapatnam",
    latitude: 17.729,
    longitude: 83.3163,
  },
  {
    id: 11,
    name: "GMR Institute of Technology, Rajam",
    latitude: 18.2921,
    longitude: 83.4164,
  },
  {
    id: 12,
    name: "Vignan's Foundation for Science, Technology & Research, Guntur",
    latitude: 16.3838,
    longitude: 80.4407,
  },
  {
    id: 13,
    name: "GITAM Institute of Technology, Visakhapatnam",
    latitude: 17.7854,
    longitude: 83.3689,
  },
  {
    id: 14,
    name: "Vasireddy Venkatadri Institute of Technology, Guntur",
    latitude: 16.5586,
    longitude: 80.5448,
  },
  {
    id: 15,
    name: "Narayana Engineering College, Nellore",
    latitude: 14.4301,
    longitude: 79.9864,
  },
  {
    id: 16,
    name: "Aditya Engineering College, Surampalem",
    latitude: 17.2356,
    longitude: 82.178,
  },
  {
    id: 17,
    name: "Velagapudi Ramakrishna Siddhartha Engineering College, Vijayawada",
    latitude: 16.467,
    longitude: 80.6151,
  },
  {
    id: 18,
    name: "Koneru Lakshmaiah Education Foundation (KLEF), Vaddeswaram",
    latitude: 16.441,
    longitude: 80.6125,
  },
  {
    id: 19,
    name: "Rajiv Gandhi University of Knowledge Technologies, Nuzvid",
    latitude: 16.7843,
    longitude: 80.8476,
  },
  {
    id: 20,
    name: "Prasad V. Potluri Siddhartha Institute of Technology, Vijayawada",
    latitude: 16.5081,
    longitude: 80.648,
  },
];
